#!/usr/bin/env python
import sys
import os
import signal
import BaseHTTPServer
from SimpleHTTPServer import SimpleHTTPRequestHandler


if sys.argv[1:]:
    port = int(sys.argv[1])
else:
    port = 8000
server_address = ('127.0.0.1', port)


def handler(signum, frame):
    os.system("open http://{}:{}".format(*server_address))

HandlerClass = SimpleHTTPRequestHandler
ServerClass  = BaseHTTPServer.HTTPServer
Protocol     = "HTTP/1.0"

HandlerClass.protocol_version = Protocol
httpd = ServerClass(server_address, HandlerClass)

sa = httpd.socket.getsockname()
print "Serving HTTP on", sa[0], "port", sa[1], "..."

os.chdir("slides")
signal.signal(signal.SIGALRM, handler)
signal.setitimer(signal.ITIMER_REAL, 3)

print "Running webserver at {}:{}. Press ctrl-c to exit.".format(*server_address)
print "The page will be opened for you in a browser window."
httpd.serve_forever()
